sudo: required

services:
  - docker

jobs:
  include:
    - stage: Prepare build container
      script:
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - docker build -f Dockerfile.install -t antsman/rpi-mongodb-install .
      - docker images
    - stage: Build mongodb
      script:
      - docker images
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - docker build -f Dockerfile.build -t antsman/rpi-mongodb-build .

  # test image
  #- docker run --rm -d --name mongodb antsman/rpi-mongodb-build
  # stop image
  #- time docker stop mongodb

