sudo: required

services:
  - docker

env:
  global:
    - MONGO_VERSION=3.2.19
    - IMAGE_PREP=antsman/rpi-mongodb-buildenv
    - IMAGE_BUILD=antsman/rpi-mongodb-build
    - CONTAINER_BUILD=rpi-mongodb-build

jobs:
  include:
    - stage: Prepare build container
      if: branch = master1
      script:
      - echo "$MONGO_VERSION"
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - docker build --build-arg MONGO_VERSION=$MONGO_VERSION -f Dockerfile.buildenv -t $IMAGE_PREP .
      - docker tag $IMAGE_PREP $IMAGE_PREP:$MONGO_VERSION
      - docker images
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $IMAGE_PREP:$MONGO_VERSION 
    - stage: Build mongodb
      script:
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - docker run --rm -d --name $CONTAINER_BUILD $IMAGE_PREP:$MONGO_VERSION sleep 1h
      - ./compile-mongo.sh $CONTAINER_BUILD $MONGO_VERSION
    - stage: Stop container
      script:
      - time docker stop $CONTAINER_NAME

