FROM antsman/rpi-mongodb-buildenv

ARG MONGO_VERSION=3.2.19

# For Mozilla virtualenv .. Exception: Could not detect environment shell!
ENV SHELL /bin/sh

RUN cd mongodb-src-r$MONGO_VERSION && \
# Build
    scons mongo mongod --wiredtiger=off --mmapv1=on && \
# Test
    cd build/opt/mongo && \
    ls -l && \
    strip -s mongo && \
    ls -l && \
    ./mongo --version && \
    ./mongod --version

COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/sh"]

